language: ruby

matrix:
  include:
    ## Test on Mac OS X 10.12
    - os: osx
      osx_image: xcode8.2
    ## Test on Mac OS X 10.11
    - os: osx
      osx_image: xcode8
    ## Test on Mac OS X 10.10
    - os: osx
      osx_image: xcode6.4

branches:
  except:
    - gh-pages

install:
    - tar xfz normaliz-3.2.0-x86_64-apple-darwin15.6.0.tar.gz

script:
    ## Just test whether the programs can be executed.
    - bin/normaliz --version
    - bin/Qnormaliz --version
    - bin/nmzIntegrate --version
    ## The distribution also contains libraries and header files;
    ## we do not attempt to test that they work.

