language: ruby

matrix:
  include:
    ## Test on Mac OS X 10.12
    - os: osx
      osx_image: xcode8.2
    ## Test on Mac OS X 10.11
    - os: osx
      osx_image: xcode8
    ## Test on Mac OS X 10.10
    - os: osx
      osx_image: xcode6.4

branches:
  except:
    - gh-pages

install:
    - tar xfz normaliz-*-x86_64-apple-darwin*.tar.gz

script:
    ## First test whether the programs can be executed.
    - bin/normaliz --version
    - bin/Qnormaliz --version
    ## Now test against the test suite, including nmzintegrate
    - git clone https://github.com/Normaliz/Normaliz.git
    - export NORMALIZ="`pwd`/bin/normaliz"
    - export NMZ_TEST_TARGETS="all testInt"
    - (cd Normaliz/test && make -j3 -f Makefile.classic $NMZ_TEST_TARGETS NORMALIZ="$NORMALIZ")
    - export QNORMALIZ="`pwd`/bin/Qnormaliz"
    - (cd Normaliz/Qtest && make -j3 -f Makefile.classic all QNORMALIZ="$QNORMALIZ")
    ## The distribution also contains libraries and header files;
    ## we do not attempt to test that they work.
