language: ruby

matrix:
  include:
    ## Test on Mac OS X 10.13
    - os: osx
      osx_image: xcode9.3beta
    ## Test on Mac OS X 10.12
    - os: osx
      osx_image: xcode9.2
    ## Test on Mac OS X 10.11
    - os: osx
      osx_image: xcode8
    ## Test on Mac OS X 10.10
    - os: osx
      osx_image: xcode6.4

branches:
  except:
    - gh-pages

install:
    - tar xfz normaliz-*-x86_64-apple-darwin*.tar.gz

script:
    ## First test whether the programs can be executed.
    - bin/normaliz --version
    ## Show shared library dependencies
    - otool -L bin/*
    ## Now test against the test suite, including integration and algebraic polyhedra
    - git clone https://github.com/Normaliz/Normaliz.git
    - export NORMALIZ="`pwd`/bin/normaliz"
    - export NMZ_TEST_TARGETS="total"
    - (cd Normaliz/test && make -j3 -k -f Makefile.classic $NMZ_TEST_TARGETS NORMALIZ="$NORMALIZ")
    ## The distribution also contains libraries and header files;
    ## we do not attempt to test that they work.
